---

all:
  vars:
    ansible_become_password: '{{ lookup("env", "ANSIBLE_BECOME_PASSWORD") }}'
  hosts:
    matrix.pikaviestin.fi:
    valvonta.pikaviestin.fi:
    mastodon.pikaviestin.fi:
    docker.pikaviestin.fi:
    mailer.pikaviestin.fi:
  children:
    matrix_synapse:
      hosts:
        matrix.pikaviestin.fi:

