---
- name: Check Traefik appdata dir
  stat:
    path: /opt/docker/appdata/traefik
  register: traefik_appdata

- name: Create Traefik appdata directory
  file:
   path: /opt/docker/appdata/traefik
   state: directory
  when: not traefik_appdata.stat.exists

- name: Check traefik rules dir
  stat:
    path: /opt/docker/appdata/traefik/rules
  register: traefik_appdata_rules

- name: Create Traefik rules directory
  file:
    path: /opt/docker/appdata/traefik/rules
    state: directory
  when: not traefik_appdata_rules.stat.exists

- name: Copy Traefik rule (tls-options)
  template:
    src: "traefik/rules/tls-options.toml"
    dest: "/opt/docker/appdata/traefik/rules/tls-options.toml"

- name: Copy Traefik rule (502-router)
  template:
    src: "traefik/rules/502-router.yaml"
    dest: "/opt/docker/appdata/traefik/rules/502-router.yaml"

- name: Check Traefik acme dir
  stat:
    path: /opt/docker/appdata/traefik/acme
  register: traefik_appdata_acme

- name: Create Traefik acme directory
  file:
    path: /opt/docker/appdata/traefik/acme/
    state: directory
  when: not traefik_appdata_acme.stat.exists

- name: Check that acme file exists for Letsencrypt
  stat:
    path: /opt/docker/appdata/traefik/acme/acme-le.json
  register: traefik_appdata_acme_file

- name: Create traefik acme file
  file:
    path: /opt/docker/appdata/traefik/acme/acme-le.json
    state: file
    mode: 644
  when: not traefik_appdata_acme_file.stat.exists

- name: Traefik Proxy network
  docker_network:
   name: traefik_proxy
   internal: true

- name: Traefik conntainer
  docker_container:
    name: traefik
    hostname: traefik
    image: traefik:v3.5.2@sha256:a25a60542eb7ad64aba73926c0f69fa454f48fbd51eeda0f60c99902d1d40a2a
    pull: yes
    image_name_mismatch: recreate
    network_mode: host
    restart_policy: unless-stopped
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=le
      - --entrypoints.websecure.http.tls.domains[0].main=login.pikaviestin.fi
      - --entrypoints.websecure.http.tls.domains[0].sans=cinny.pikaviestin.fi,chat.pikaviestin.fi
      - --entrypoints.websecure.http.tls.domains[1].main=docker.pikaviestin.fi
      - --entrypoints.websecure.http.tls.domains[2].main=sliding-sync.matrix.pikaviestin.fi
      - --api=true
      - --api.insecure=true
      - --api.dashboard=true
      - --log=true
      - --log.level=INFO
      - --accessLog=true
      - --accessLog.filePath=/logs/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499,500
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik_proxy
      - --providers.file.directory=/config/rules
      - --providers.file.watch=true
      - --certificatesResolvers.le.acme.email={{ certbot_admin_email }}
      - --certificatesResolvers.le.acme.storage=/config/acme/acme-le.json
      - --certificatesResolvers.le.acme.keyType=EC384
      - --certificatesResolvers.le.acme.tlsChallenge
    volumes:
      - /opt/docker/appdata/traefik:/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
